src/Entity/Problem.php
<?php

namespace App\Entity;

use App\Repository\ProblemRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProblemRepository::class)
 * @ORM\HasLifecycleCallbacks()
 */
class Problem
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $start_at;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_end;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="datetime")
     */
    private $create_at;

    /**
     * @ORM\ManyToMany(targetEntity=Zone::class, inversedBy="problems")
     */
    private $zone;

    /**
     * @ORM\ManyToOne(targetEntity=Compagnie::class, inversedBy="problems")
     * @ORM\JoinColumn(nullable=false)
     */
    private $compagnie;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="problems")
     */
    private $author;


    public function __construct()
    {
        $this->zone = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getStartAt(): ?\DateTimeInterface
    {
        return $this->start_at;
    }

    public function setStartAt(\DateTimeInterface $start_at): self
    {
        $this->start_at = $start_at;

        return $this;
    }

    public function getIsEnd(): ?bool
    {
        return $this->is_end;
    }

    public function setIsEnd(?bool $is_end): self
    {
        $this->is_end = $is_end;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeInterface
    {
        return $this->create_at;
    }

    public function setCreateAt(\DateTimeInterface $create_at): self
    {
        $this->create_at = $create_at;

        return $this;
    }

    /**
     * @return Collection|Zone[]
     */
    public function getZone(): Collection
    {
        return $this->zone;
    }

    public function addZone(Zone $zone): self
    {
        if (!$this->zone->contains($zone)) {
            $this->zone[] = $zone;
        }

        return $this;
    }

    public function removeZone(Zone $zone): self
    {
        $this->zone->removeElement($zone);

        return $this;
    }

    public function getCompagnie(): ?Compagnie
    {
        return $this->compagnie;
    }

    public function setCompagnie(?Compagnie $compagnie): self
    {
        $this->compagnie = $compagnie;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @ORM\PrePersist
     */
    function persiste()
    {
        $this->create_at = new \DateTime();
    }
}

src/Entity/Zone.php
<?php

namespace App\Entity;

use App\Repository\ZoneRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ZoneRepository::class)
 * @ORM\HasLifecycleCallbacks()
 */
class Zone
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="datetime")
     */
    private $create_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $update_at;

    /**
     * @ORM\ManyToMany(targetEntity=Problem::class, mappedBy="zone")
     */
    private $problems;

    public function __construct()
    {
        $this->problems = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeInterface
    {
        return $this->create_at;
    }

    public function setCreateAt(\DateTimeInterface $create_at): self
    {
        $this->create_at = $create_at;

        return $this;
    }

    public function getUpdateAt(): ?\DateTimeInterface
    {
        return $this->update_at;
    }

    public function setUpdateAt(\DateTimeInterface $update_at): self
    {
        $this->update_at = $update_at;

        return $this;
    }


    /**
     * @return Collection|Problem[]
     */
    public function getProblems(): Collection
    {
        return $this->problems;
    }

    public function addProblem(Problem $problem): self
    {
        if (!$this->problems->contains($problem)) {
            $this->problems[] = $problem;
            $problem->addZone($this);
        }

        return $this;
    }

    public function removeProblem(Problem $problem): self
    {
        if ($this->problems->removeElement($problem)) {
            $problem->removeZone($this);
        }

        return $this;
    }
    /**
     * @ORM\PrePersist
     */
    function persiste()
    {
        $this->create_at = new \DateTime();
        $this->update_at = new \DateTime();
    }

    /**
     * @ORM\PreUpdate
     */
    function update()
    {
        $this->update_at = new \DateTime();
    }

    public function __toString(){
        return $this->name;
    }
}

src/Controller/ProfileController.php
<?php

namespace App\Controller;

use App\Entity\Problem;
use App\Form\ProblemType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ProfileController extends AbstractController
{
    /**
     * @Route("/profile", name="profile")
     */
    public function index(Request $req ): Response
    {
        $problem = new Problem();
        $problem->setAuthor($this->getUser());
        $problem_form = $this->createForm(ProblemType::class,$problem);
        $problem_form->handleRequest($req);
        if ($problem_form->isSubmitted() && $problem_form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($problem);
            $em->flush();
            return $this->redirectToRoute("profile");
        }
        return $this->render('profile/index.html.twig', [
            'problem_form' => $problem_form->createView(),
        ]);
    }
}

templates/profile/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ProfileController!
{% endblock %}
{% block slider %}{% endblock %}

{% block body %}
	<div class="container mt-5">
		<section>
			<div class="row">
				<div class="col-sm-8 mb-4">
					<div class="card">
						<div class="card-body">
							<div class="d-flex justify-content-between p-md-1">
								<div class="d-flex flex-row">
									<div class="align-self-center">
										<i class="fas fa-pencil-alt text-info fa-3x me-4"></i>
									</div>
									<div>
										<h4>
											{% trans %}Mes plaintes{% endtrans %}</h4>
									</div>
								</div>
								<div class="align-self-center">
									<h2 class="h1 mb-0">{{ app.user.problems |length }}</h2>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>

		</section>
	</div>

	<div
		class="container">
		<!-- Button trigger modal -->
		<button type="button" class="btn btn-primary" data-mdb-toggle="modal" data-mdb-target="#exampleModal">
			{% trans %}Signaler un probleme{% endtrans %}
		</button>

		<!-- Modal -->
		<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
			<div class="modal-dialog modal-dialog-scrollable">
				<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title" id="exampleModalLabel">{% trans %}Nouvelle plainte{% endtrans %}</h5>
						<button type="button" class="btn-close" data-mdb-dismiss="modal" aria-label="Close"></button>
					</div>
					<div class="modal-body ">
						{{ form(problem_form) }}
						</div>
						<div class="modal-footer">
							<button type="button" class="btn btn-secondary" data-mdb-dismiss="modal">
								{% trans %}Fermer{% endtrans %}
							</button>
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				{% for problem in app.user.problems %}

					<div class="col-sm-6 col-md-4 col-lg-3 mt-2 mb-2">
						<div class="card">
							<div class="card-body">
								<h5 class="card-title">{{problem.title}}</h5>
								<h6 class="card-subtitle mb-2 text-muted">{{problem.compagnie.name}}</h6>
								<p class="card-text">
									{{ problem.description }}
								</p>
								<p class="card-text">
									{{ problem.createAt |date("m/d/Y") }}
								</p>
								<a href="#" class="card-link">{% trans %}Voir{% endtrans %}</a>

								{% if not problem.isEnd %}
									<a href="#" class="card-link text-success">{% trans %}Resolue{% endtrans %}</a>
								{% endif %}
							</div>
						</div>
					</div>

				{% endfor %}
			</div>
		</div>
	{% endblock %}